name = "OLYCITY V1"
author = "OLYCITY"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2bfa17237bae5d7daa9683f3b54692807f9ab42a812050dd140e0d881fc688"

[versions]
minecraft = "1.20.1"
forge = "47.4.10"
