name = "OLYCITY V1"
author = "OLYCITY"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "915ea8e56538e17f2697b48bc679ff13f08460a551bd5a74b4e8afcbad0cab97"

[versions]
minecraft = "1.20.1"
forge = "47.4.10"
